// SPDX-License-Identifier: MIT
//
// Clean-room. Not adapted from obsidian-copilot.
//
// The @neuro agent loop. Given a user message that starts with `@neuro`, we:
//
//   1. Load the system prompt (cached).
//   2. Load the tool manifest (cached) — tv_* tools + skill shims.
//   3. Call `llm.tool_use()` in a bounded loop. Each turn either:
//         - yields a final text answer (stop), or
//         - yields tool_calls we must execute and feed back.
//   4. Before executing any write-intent tool, run the safety gates.
//      A refusal is surfaced to the agent as a tool-result (so it can retry
//      with a different tool), never as a raw error.
//   5. Every tool call — allowed, refused, or errored — logs to the trace.
//   6. Tool results are wrapped in <tool-result id="..."> ... </tool-result>
//      delimiters. The system prompt tells the agent to treat their contents
//      as data, not instructions.
//   7. A cumulative token budget (default 500K across input + output) aborts
//      the loop with a "token budget exceeded" stop rather than running
//      indefinitely.

import type {
  LLMChatOptions,
  LLMChatResult,
  LLMMessage,
  LLMToolCall,
  LLMToolDefinition,
} from "../providers/base";
import { checkWriteSafety, type SafetyContext, type SafetyRefusal } from "./safety-gates";
import type { TraceLogger } from "./trace-logger";

/** Dependency-injected LLM surface — a subset of LLMManager. */
export interface AgentLLM {
  tool_use(opts: LLMChatOptions): Promise<LLMChatResult>;
  defaultModel(): string;
}

export interface AgentConfig {
  /** Hard upper bound on tool-use rounds. */
  maxTurns?: number;
  /** Cumulative (input+output) token cap across the whole loop. */
  tokenBudget?: number;
  /** Path-safety context (allowed globs). */
  safety?: SafetyContext;
  /** Optional model override (defaults to llm.defaultModel()). */
  model?: string;
  /** Max tokens per individual turn. */
  maxTokensPerTurn?: number;
  /** Conversation id used for log correlation. */
  conversationId?: string;
}

export const DEFAULT_MAX_TURNS = 20;
export const DEFAULT_TOKEN_BUDGET = 500_000;
export const DEFAULT_MAX_TOKENS_PER_TURN = 4096;

const NEURO_REGEX = /^\s*@neuro\b/i;

/**
 * `true` if the user message should be routed through the agent loop.
 */
export function detectNeuroMode(userMessage: string): boolean {
  return NEURO_REGEX.test(userMessage);
}

export interface AgentDeps {
  llm: AgentLLM;
  tools: LLMToolDefinition[];
  systemPrompt: string;
  /**
   * Executor that actually runs a tool call. Returns a JSON-encodable object
   * that will be stringified into the tool-result envelope. A thrown error
   * is caught and surfaced to the agent as an "error" tool-result (logged
   * separately). Safety refusals are generated by the loop itself — the
   * executor is only called for allowed calls.
   */
  executor: (call: LLMToolCall) => Promise<unknown>;
  trace: TraceLogger;
  /** Optional abort signal — aborts the loop cleanly at the next turn boundary. */
  signal?: AbortSignal;
}

export interface AgentTurn {
  messages: LLMMessage[];
  toolCalls: Array<{ call: LLMToolCall; outcome: "ok" | "refused" | "error"; result: string }>;
  finalContent: string;
  stopReason:
    | "stop"
    | "max_turns"
    | "token_budget"
    | "aborted"
    | "error";
  tokenUsage: { input: number; output: number };
}

export class NeuroAgent {
  private deps: AgentDeps;
  private cfg: Required<Omit<AgentConfig, "safety" | "model" | "conversationId">> & {
    safety?: SafetyContext;
    model?: string;
    conversationId?: string;
  };

  constructor(deps: AgentDeps, cfg: AgentConfig = {}) {
    this.deps = deps;
    this.cfg = {
      maxTurns: cfg.maxTurns ?? DEFAULT_MAX_TURNS,
      tokenBudget: cfg.tokenBudget ?? DEFAULT_TOKEN_BUDGET,
      maxTokensPerTurn: cfg.maxTokensPerTurn ?? DEFAULT_MAX_TOKENS_PER_TURN,
      safety: cfg.safety,
      model: cfg.model,
      conversationId: cfg.conversationId,
    };
  }

  async run(userMessage: string, history: LLMMessage[] = []): Promise<AgentTurn> {
    const messages: LLMMessage[] = [
      { role: "system", content: this.deps.systemPrompt },
      ...history,
      { role: "user", content: userMessage },
    ];
    const executed: AgentTurn["toolCalls"] = [];
    let inputTokens = 0;
    let outputTokens = 0;
    let stopReason: AgentTurn["stopReason"] = "stop";
    let finalContent = "";

    const model = this.cfg.model ?? this.deps.llm.defaultModel() ?? "";

    for (let turn = 0; turn < this.cfg.maxTurns; turn++) {
      if (this.deps.signal?.aborted) {
        stopReason = "aborted";
        break;
      }
      if (inputTokens + outputTokens > this.cfg.tokenBudget) {
        stopReason = "token_budget";
        break;
      }

      let result: LLMChatResult;
      try {
        result = await this.deps.llm.tool_use({
          model,
          messages,
          tools: this.deps.tools,
          maxTokens: this.cfg.maxTokensPerTurn,
          signal: this.deps.signal,
        });
      } catch (e) {
        stopReason = "error";
        finalContent = `Agent error: ${(e as Error).message}`;
        break;
      }

      inputTokens += result.usage?.inputTokens ?? 0;
      outputTokens += result.usage?.outputTokens ?? 0;

      // Record the assistant's turn — content plus any tool-call intents.
      const assistantMsg: LLMMessage = {
        role: "assistant",
        content: result.content ?? "",
      };
      if (result.tool_calls && result.tool_calls.length > 0) {
        assistantMsg.tool_calls = result.tool_calls;
      }
      messages.push(assistantMsg);

      // Terminal cases: no tool calls, or non-tool_use finish reason.
      const hasToolCalls = !!(result.tool_calls && result.tool_calls.length > 0);
      if (!hasToolCalls || result.finishReason !== "tool_calls") {
        finalContent = result.content ?? "";
        stopReason = "stop";
        break;
      }

      // Execute each tool call sequentially. Safety gates run per-call;
      // refusals are fed back so the agent can self-correct mid-loop.
      for (const call of result.tool_calls!) {
        const refusal = checkWriteSafety(call.name, call.arguments, this.cfg.safety);
        if (refusal) {
          const envelope = wrapRefusal(call.id, refusal);
          executed.push({ call, outcome: "refused", result: envelope });
          messages.push(toolResultMessage(call.id, envelope));
          await this.deps.trace.append({
            callId: call.id,
            tool: call.name,
            arguments: call.arguments,
            outcome: "refused",
            summary: refusal.message,
            conversationId: this.cfg.conversationId,
          });
          continue;
        }

        let outcome: "ok" | "error" = "ok";
        let resultValue: string;
        try {
          const raw = await this.deps.executor(call);
          resultValue = stringifyToolResult(raw);
        } catch (e) {
          outcome = "error";
          resultValue = JSON.stringify({
            error: (e as Error).message || "tool execution failed",
          });
        }
        const envelope = wrapToolResult(call.id, resultValue);
        executed.push({ call, outcome, result: envelope });
        messages.push(toolResultMessage(call.id, envelope));
        await this.deps.trace.append({
          callId: call.id,
          tool: call.name,
          arguments: call.arguments,
          outcome,
          summary: outcome === "error" ? resultValue.slice(0, 240) : undefined,
          conversationId: this.cfg.conversationId,
        });

        // Budget check between calls so a very chatty turn can't blow past
        // the cap on pure tool-result size.
        if (inputTokens + outputTokens > this.cfg.tokenBudget) {
          stopReason = "token_budget";
          break;
        }
      }

      if (stopReason === "token_budget") break;

      // Continue the loop — the next turn will feed the tool results back
      // to the model so it can produce a final text answer.
      if (turn === this.cfg.maxTurns - 1) {
        // We've done maxTurns iterations without a natural stop.
        stopReason = "max_turns";
      }
    }

    return {
      messages,
      toolCalls: executed,
      finalContent,
      stopReason,
      tokenUsage: { input: inputTokens, output: outputTokens },
    };
  }
}

// ── envelope helpers ──────────────────────────────────────────────────────

/**
 * Wrap a successful tool-result payload in the delimiter the system prompt
 * tells the agent to treat as untrusted data. The `id` is the tool_call.id
 * so the model can correlate.
 */
export function wrapToolResult(id: string, payload: string): string {
  // Scrub any embedded closing delimiter in the payload to prevent the
  // delimiter-escape attack. We replace `</tool-result>` with a visible
  // placeholder so legitimate content containing that substring doesn't
  // get silently dropped — the model sees it was tampered with.
  const safe = payload.replace(/<\/tool-result>/gi, "</tool-result_ESCAPED>");
  return `<tool-result id="${escapeAttr(id)}">\n${safe}\n</tool-result>`;
}

export function wrapRefusal(id: string, refusal: SafetyRefusal): string {
  const body = JSON.stringify({
    refused: true,
    tool: refusal.tool,
    reason: refusal.reason,
    path: refusal.path,
    message: refusal.message,
  });
  return wrapToolResult(id, body);
}

function escapeAttr(s: string): string {
  return s.replace(/"/g, "&quot;").replace(/</g, "&lt;");
}

function toolResultMessage(id: string, envelope: string): LLMMessage {
  return {
    role: "tool",
    content: envelope,
    tool_call_id: id,
  };
}

function stringifyToolResult(raw: unknown): string {
  if (typeof raw === "string") return raw;
  try {
    return JSON.stringify(raw);
  } catch {
    return String(raw);
  }
}
